/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import beans.DatabaseRemote;
import beans.Machines;
import beans.Momenten;
import beans.Reservaties;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.TableColumn;

/**
 *
 * @author Max
 */
public class Gui extends javax.swing.JFrame {

    /**
     * Creates new form Gui
     */
    private DatabaseRemote db;
    private List<Machines> machines;
    private List<Momenten> momenten;
    private String[] colNames = {"Mnr", "Naam", "Locatie"};
    private Object[][] rowData;
    
    private String[] colNames2 = {"MomID", "Starttijd", "Duur"};
    private Object[][] rowData2;
    
    public Gui(DatabaseRemote db) {
        this.db = db;
        this.machines = db.getMachines();
        rowData = new Object[machines.size()][3];

                //init tabel
        int i = 0;
        for(Machines machine : this.machines){
            rowData[i][0] = machine.getMnr();
            rowData[i][1] = machine.getMnaam();
            rowData[i][2] = machine.getMloc();
            i++;
        }
        
        initComponents();
        
            //init detail paneel
        detailPanel.setSize(this.getSize());
        this.setContentPane(overzichtPanel);
        
        
        Machinetbl.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 1) {
                    JTable target = (JTable)e.getSource();
                    int row = target.getSelectedRow();
                    //int column = target.getSelectedColumn();
                    
                    
                    Machines machine = machines.get(row);
                    System.out.println(machine.getMnaam());
                    toonMachine(machine);
                }
            }
        });
        
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        overzichtPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Machinetbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        detailPanel = new javax.swing.JPanel();
        terugKnop = new javax.swing.JButton();
        naamLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Machinetbl.setModel(new javax.swing.table.DefaultTableModel(
            rowData, colNames
        ));
        Machinetbl.setColumnSelectionAllowed(true);
        Machinetbl.setDefaultEditor(Object.class, null);
        jScrollPane1.setViewportView(Machinetbl);

        jLabel1.setText("Overzicht van de machines");

        javax.swing.GroupLayout overzichtPanelLayout = new javax.swing.GroupLayout(overzichtPanel);
        overzichtPanel.setLayout(overzichtPanelLayout);
        overzichtPanelLayout.setHorizontalGroup(
            overzichtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overzichtPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(overzichtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        overzichtPanelLayout.setVerticalGroup(
            overzichtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, overzichtPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        terugKnop.setText("Terug");
        terugKnop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terugKnopActionPerformed(evt);
            }
        });

        naamLabel.setText("jLabel1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout detailPanelLayout = new javax.swing.GroupLayout(detailPanel);
        detailPanel.setLayout(detailPanelLayout);
        detailPanelLayout.setHorizontalGroup(
            detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(naamLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(terugKnop))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE))
                .addContainerGap())
        );
        detailPanelLayout.setVerticalGroup(
            detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(naamLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(terugKnop)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(overzichtPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(150, 150, 150)
                    .addComponent(detailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(overzichtPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(105, 105, 105)
                    .addComponent(detailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void terugKnopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terugKnopActionPerformed
        // TODO add your handling code here:
        this.setContentPane(overzichtPanel);
        this.repaint();
        this.revalidate();
    }//GEN-LAST:event_terugKnopActionPerformed

    private void toonMachine(Machines m){
        //this.momenten = this.db.getMomenten();
        List<Momenten> momentenlijst = db.getMachineMomenten(m);
        List<Reservaties> reservatielijst = db.getReservaties(m.getMnr().intValue());
        rowData2 = new Object[reservatielijst.size()][3];
        
        int i = 0;
        for(Reservaties res : reservatielijst){
            rowData2[i][0] = res.getRnr();
            rowData2[i][1] = res.getUur();
            rowData2[i][2] = res.getDuur();
            System.out.println("\tResID: " + res.getRnr() + "  Starttijd: " + res.getUur() + "  Duur: " + res.getDuur() + "  Gebruiker: " + res.getGebruikersnaam());
            i++;
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(rowData2, colNames2));
        jTable1.setDefaultEditor(Object.class, null);
        this.setContentPane(detailPanel);
        naamLabel.setText(m.getMnaam());
        this.repaint();
        this.revalidate();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Gui("test").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Machinetbl;
    private javax.swing.JPanel detailPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel naamLabel;
    private javax.swing.JPanel overzichtPanel;
    private javax.swing.JButton terugKnop;
    // End of variables declaration//GEN-END:variables
}
